### PR TITLE
Switch to Just-the-Docs, fix formatting for new theme

### LINKED ISSUE #4: Better layout / theme
I believe it would be more accessible if this used a theme such as [Just the Docs](https://github.com/pmarsceill/just-the-docs), which would provide easier navigation and search functionality. (This is something I'm actively working on, at least for myself, and would like to contribute it back if possible).

### PR DESCRIPTION
**Pull request by nobodywasishere**
- Closes #4

### CODE REVIEW

**Comment by nobodywasishere** [comment]
Anything I need to do for this to be merged?

**Comment by maksimdrachov** [comment]
hi sorry,

Will take a look tomorrow; promise :)

**Comment by nobodywasishere** [comment]
Thank you! No pressure!

**Comment by maksimdrachov** [comment]
Nice work!

**Pull request merged**
