### PR TITLE
fix(basic-sample): update include to resolve deprecation warning

### PR DESCRIPTION
**Pull request by maarten1C96**
Replaced `<zephyr/zephyr.h>` with `<zephyr/kernel.h>` based on the following compilation warning raised:

	#warning "<zephyr/zephyr.h> is deprecated, include <zephyr/kernel.h> instead" [-Wcpp]

Note: This change has been applied to the basic-sample only. Most likely other samples in the project might require the same update.

### CODE REVIEW

**Comment by maksimdrachov** [comment]
image


[Left](https://github.com/maksimdrachov/zephyr-rtos-tutorial/blob/a63b0dfeb719f4cfd42cfead2bc68cb00f3f2b29/docs/1-zephyr-setup/install/mac-os.md) is commit right before yours, right is your [commit](https://github.com/maksimdrachov/zephyr-rtos-tutorial/blob/d87df43d697390afc81879e8ab6aadffa1519b95/docs/1-zephyr-setup/install/mac-os.md).

I merged it but then noticed this, so if you could fix this and re-submit? :)

**Comment by maarten1C96** [comment]
I would first like to mention I am _not_ yet an expert in working with Git yet (this is one of my first pull requests). Having said that: 

1. Could the reason the image works in your version be that it has already been built/processed by Jekyll, while my commit is not showing any images because they have not been touched by Jekyll yet?
2. Why is your version on the left actually showing a working image anyway? Are the images also working when [visiting  your Pages](https://maksimdrachov.github.io/zephyr-rtos-tutorial/docs/1-zephyr-setup/install/mac-os.html) in your webbrowser?

**Comment by maarten1C96** [comment]
Ah, I now understand better that the current images are indeed functional in your repository when accessed via the _GitHub web interface_, only not via _GitHub Pages_ (and my commit probably makes them work on GitHub Pages only, but possibly disrupting their display in the original web interface). This issue might be resolved by incorporating something like `{{ site.baseurl }}` into the file paths. Could you share a screenshot of your GitHub Pages configuration, so I can replicate your configuration and test things out on my own fork first? Like the following:

Screenshot 2024-04-07 at 11 40 22 3

**Comment by maksimdrachov** [comment]
Hi,

> I would first like to mention I am not yet an expert in working with Git yet 

That's okay, we all have to start somewhere :)

Here you go:

image

**Pull request merged**
